In [1]:
a = (4, 5, 6)

In [2]:
(a, b, c) = a

In [3]:
b

5

In [4]:
a = (4, 5, (6, 7))

In [6]:
(a, b, (c, d)) = a

In [7]:
c

6

In [11]:
a = (4, 5, 6, 7)

In [12]:
a, b, *rest = a

In [13]:
a, b

(4, 5)

In [14]:
a = (4, 5, 5, 5, 5, 6, 7)

In [15]:
a.count(5)

4

In [16]:
a = (4, 5, 6, 7)

In [17]:
b_list = list(a)

In [18]:
b_list

[4, 5, 6, 7]

In [19]:
b_list[2]=8

In [20]:
b_list

[4, 5, 8, 7]

In [21]:
b_list.append(8)

In [22]:
b_list

[4, 5, 8, 7, 8]

In [23]:
b_list.insert(1,2)

In [24]:
b_list

[4, 2, 5, 8, 7, 8]

In [25]:
b_list.pop(3)

8

In [26]:
b_list

[4, 2, 5, 7, 8]

In [28]:
b_list.append(5)

In [29]:
b_list

[4, 2, 5, 7, 8, 5]

In [30]:
b_list.remove(5)

In [31]:
b_list

[4, 2, 7, 8, 5]

In [32]:
2 in b_list

True

In [33]:
7 not in b_list

False

In [34]:
a = [4, 5, 6, 7]

In [35]:
a.extend([8,9,(10, 11)])

In [36]:
a

[4, 5, 6, 7, 8, 9, (10, 11)]

In [38]:
a = [4,8, 9, 6, 5]

In [40]:
a.sort()

In [41]:
a

[4, 5, 6, 8, 9]

In [43]:
a=['apple', 'bag', 'fork', 'hospital']

In [44]:
a.sort(key=len)

In [45]:
a

['bag', 'fork', 'apple', 'hospital']

In [46]:
import bisect

In [47]:
a = [2, 4, 5, 6, 7]

In [48]:
bisect.bisect(a,2)

1

In [49]:
bisect.bisect(a,5)

3

In [50]:
bisect.insort(a,4)

In [51]:
a

[2, 4, 4, 5, 6, 7]

In [52]:
a[1:3]

[4, 4]

In [53]:
a[1:3]=[3,4]

In [54]:
a

[2, 3, 4, 5, 6, 7]

In [55]:
a[:-2]

[2, 3, 4, 5]

In [57]:
a[::2]

[2, 4, 6]

In [58]:
a[::-1]

[7, 6, 5, 4, 3, 2]

In [59]:
some_list = ['foo', 'bar', 'baz']

In [60]:
mapping = {}

In [61]:
for i, value in enumerate(some_list):
    mapping[value] = i

In [62]:
mapping

{'foo': 0, 'bar': 1, 'baz': 2}

In [71]:
a = [4, 6, 8, 2, 9, 3]

In [72]:
sorted (a)

[2, 3, 4, 6, 8, 9]

In [73]:
b = ['a', 'b', 'c', 'd', 'e', 'f']

In [74]:
c =zip(a,b)

In [75]:
list(c)

[(4, 'a'), (6, 'b'), (8, 'c'), (2, 'd'), (9, 'e'), (3, 'f')]

In [78]:
list(reversed(range(9)))

[8, 7, 6, 5, 4, 3, 2, 1, 0]

empty_dict = {}

In [89]:
d1 = {'a': '1', 'b':'2'}

In [90]:
d1

{'a': '1', 'b': '2'}

In [91]:
d1['f'] = '3'

In [92]:
d1

{'a': '1', 'b': '2', 'f': '3'}

In [93]:
d1['b']

'2'

In [94]:
del d1['b']

In [95]:
d1

{'a': '1', 'f': '3'}

In [96]:
d1.update({'g':'4'})

In [97]:
d1

{'a': '1', 'f': '3', 'g': '4'}

In [98]:
d1.update({'g':'7'})

In [99]:
d1

{'a': '1', 'f': '3', 'g': '7'}

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 46.9 ms
Wall time: 29.5 ms


In [5]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: total: 625 ms
Wall time: 630 ms


In [6]:
data = np.random.randn (2,3)

In [7]:
data

array([[-0.66587884,  0.1949177 ,  0.06641323],
       [ 0.66734361, -0.41195767, -0.56635463]])

In [8]:
data * 10

array([[-6.65878838,  1.94917699,  0.66413226],
       [ 6.67343612, -4.11957669, -5.66354632]])

In [9]:
data + data

array([[-1.33175768,  0.3898354 ,  0.13282645],
       [ 1.33468722, -0.82391534, -1.13270926]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data1 = [4, 6, 2, 8, 9]

In [13]:
arr1 = np.array(data1)

In [14]:
arr1

array([4, 6, 2, 8, 9])

In [16]:
data2 = [[2, 3, 5, 7],[4, 6, 8, 10]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[ 2,  3,  5,  7],
       [ 4,  6,  8, 10]])

In [19]:
arr2.shape

(2, 4)

In [21]:
arr1.dtype

dtype('int64')

In [22]:
arr2.dtype

dtype('int64')

In [23]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [27]:
arr = np.array ([[2, 4, 6], [8, 10, 12]])

In [28]:
48 / arr

array([[24. , 12. ,  8. ],
       [ 6. ,  4.8,  4. ]])

In [29]:
arr * 2

array([[ 4,  8, 12],
       [16, 20, 24]])

In [30]:
arr2 = np.array([[2, 3, 4],[4, 5, 6]])

In [31]:
arr > arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [32]:
arr = np.arange(10)

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr[5:8]

array([5, 6, 7])

In [35]:
arr[5:8] = 12

In [36]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [40]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [42]:
arr2[1]

array([4, 5, 6])

In [43]:
arr2[0]

array([1, 2, 3])

In [45]:
arr2[2,1]

np.int64(8)

In [46]:
name = np.array(['apple','pen','book','pen'])

In [47]:
name

array(['apple', 'pen', 'book', 'pen'], dtype='<U5')

In [48]:
data = np.random.randn(4,4)

In [49]:
data

array([[ 0.10576791, -0.45773209, -0.42371595, -0.26876556],
       [-0.27568454,  0.12735846,  0.58245871, -0.09088769],
       [-0.42864811,  0.27020645, -1.84183964,  0.16703221],
       [-0.73483155,  0.08146698,  0.1766533 , -0.91965239]])

In [50]:
name == 'pen'

array([False,  True, False,  True])

In [51]:
data[name == 'pen']

array([[-0.27568454,  0.12735846,  0.58245871, -0.09088769],
       [-0.73483155,  0.08146698,  0.1766533 , -0.91965239]])

In [52]:
data[name == 'pen', 3]

array([-0.09088769, -0.91965239])

In [53]:
name != 'pen'

array([ True, False,  True, False])

In [54]:
data[name == 'pen'] = 3

In [55]:
data

array([[ 0.10576791, -0.45773209, -0.42371595, -0.26876556],
       [ 3.        ,  3.        ,  3.        ,  3.        ],
       [-0.42864811,  0.27020645, -1.84183964,  0.16703221],
       [ 3.        ,  3.        ,  3.        ,  3.        ]])

In [56]:
arr = np.arange(8)

In [57]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [58]:
arr = np.arange(8). reshape(2,4)

In [59]:
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [60]:
arr.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [63]:
arr = np.arange(16). reshape((2,2,4))

In [64]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [65]:
arr.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [66]:
arr = np.arange(6)

In [67]:
arr

array([0, 1, 2, 3, 4, 5])

In [68]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [69]:
np.exp(arr)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [71]:
arr2 = np.random.randn(6)

In [72]:
arr2

array([-0.67513708,  0.47041261,  0.14622716,  0.04949032,  1.00395674,
        0.05420702])

In [73]:
np.maximum(arr, arr2)

array([0., 1., 2., 3., 4., 5.])

In [74]:
x = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [75]:
y = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [76]:
c = np.array([True, False, True, True, False])

In [77]:
result = np.where(c,x,y)

In [78]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [79]:
arr = np.random.randn(2,2)

In [80]:
arr

array([[-0.72750217,  0.78525922],
       [ 1.02259321,  0.81735171]])

In [81]:
arr>0

array([[False,  True],
       [ True,  True]])

In [82]:
result = np.where(arr>0,1,0)

In [83]:
result

array([[0, 1],
       [1, 1]])

In [85]:
arr.mean()

np.float64(0.4744254920273385)

In [86]:
arr.sum()

np.float64(1.897701968109354)

In [87]:
(arr>0).sum()

np.int64(3)

In [88]:
(arr>0).any()

np.True_

In [89]:
(arr>0).all()

np.False_

In [90]:
arr=np.random.randn(8)

In [91]:
arr

array([-0.01868717, -0.54959075,  0.42717973,  0.2096907 , -0.02582975,
       -0.15807096, -2.16887426,  0.56844994])

In [92]:
arr.sort()

In [93]:
arr

array([-2.16887426, -0.54959075, -0.15807096, -0.02582975, -0.01868717,
        0.2096907 ,  0.42717973,  0.56844994])

In [94]:
import pandas as pd

In [96]:
from pandas import Series, DataFrame

In [97]:
obj = pd.Series([3, 4, 5, 6])

In [98]:
obj

0    3
1    4
2    5
3    6
dtype: int64

In [99]:
obj.values

array([3, 4, 5, 6])

In [100]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [101]:
obj[3]

np.int64(6)

In [103]:
obj[[3,1]]

3    6
1    4
dtype: int64

In [104]:
obj*2

0     6
1     8
2    10
3    12
dtype: int64

In [105]:
np.exp(obj)

0     20.085537
1     54.598150
2    148.413159
3    403.428793
dtype: float64

In [108]:
2 in obj*2

True

In [109]:
pd.isnull(obj)

0    False
1    False
2    False
3    False
dtype: bool

In [110]:
pd.notnull(obj)

0    True
1    True
2    True
3    True
dtype: bool

In [111]:
obj.name = 'score'

In [112]:
obj.index.name = 'ID'

In [113]:
obj

ID
0    3
1    4
2    5
3    6
Name: score, dtype: int64

In [115]:
obj.index= ['a', 'b', 'c', 'd']

In [116]:
obj

a    3
b    4
c    5
d    6
Name: score, dtype: int64

In [117]:
data = {'ID':[1,2,3],'Score':[100,99,66],'Rank':[1,2,3]}

In [118]:
frame = pd.DataFrame(data)

In [119]:
frame

ID  Score  Rank
0   1    100     1
1   2     99     2
2   3     66     3

In [120]:
frame.head(1)

ID  Score  Rank
0   1    100     1

In [121]:
frame['Score']

0    100
1     99
2     66
Name: Score, dtype: int64

In [123]:
del frame['Rank']

In [124]:
frame

ID  Score
0   1    100
1   2     99
2   3     66

In [125]:
frame.T

0   1   2
ID       1   2   3
Score  100  99  66